apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-cost-engine
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      serviceAccountName: cloud-cost-engine-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: dmitryzhuravlev/cloud-optimization-engine:latest
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "PROJECT_ID"
            - name: SLACK_WEBHOOK_URL
              valueSource:
                secretKeyRef:
                  secret: slack-webhook-url
                  version: latest
          ports:
            - containerPort: 8080
